name: GitHub Actions Demo
on:
  push:
    tags:
      - '*'

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: make build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/notify_slack"
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
